server:
  # springboot工程默认运行端口
  port: 8080
  # 绑定到所有外部接口
  address: 0.0.0.0

spring:
  datasource:
#    驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
#    数据库地址
    # url: jdbc:mysql://localhost:3306/mybatis # 可以简写为这个，其中mybatis是数据库名称
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    用户名
    username: root
#    密码
    password: 123456
  thymeleaf:
    check-template-location: false
    
mybatis:
  configuration:
    # 指定mybatis日志输出到控制台
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    # 驼峰命名
    map-underscore-to-camel-case: true

app:
  xml:
    storage:
      path: "XMLFiles/"

milvus:
  python:
    insert:
      url: http://localhost:8000/milvus/insert
    search:
      url: http://localhost:8000/milvus/search
